### ISSUE TITLE
Terraform wants to replace fresh imported peering

### ISSUE THREAD

**Issue by rfoprest** [RedisLabs/terraform-provider-rediscloud#102]
Hi there,

I imported a manually created redis peering on terraform, but once it's done, terraform wants to replace it even though the import was successfull.

### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/google v3.51.0     
+ provider registry.terraform.io/hashicorp/google-beta v3.51.0
+ provider registry.terraform.io/hashicorp/random v3.1.0      
+ provider registry.terraform.io/hashicorp/vault v2.19.0      
+ provider registry.terraform.io/redislabs/rediscloud v0.2.1

### Affected Resource(s)
- rediscloud_subscription_peering

### Terraform Configuration Files
```hcl
resource "random_password" "password" {
  length  = 20
  upper   = true
  lower   = true
  number  = true
  special = false
}

resource "rediscloud_subscription" "subscription" {
  name = var.theseus_back_project_id
  persistent_storage_encryption = false
  cloud_provider {
    provider = "GCP"
    region {
      region                                        = var.region
      networking_deployment_cidr    = var.redissubnet
      multiple_availability_zones         = true
      preferred_availability_zones        = ["europe-west1-a", "europe-west1-b", "europe-west1-c"]
    }
  }
  database {
    name                                               = "mydb"
    protocol                                          = "redis"
    memory_limit_in_gb                       = 10
    data_persistence                            = "none"
    throughput_measurement_by       = "number-of-shards"
    throughput_measurement_value  = 2
    password                                       = random_password.password.result
  }
  depends_on = [google_project_service.rediscloud_service]
}

data "google_compute_network" "network" {
  project = var.projectid
  name    = var.networkname
}

resource "rediscloud_subscription_peering" "subscription-peering" {
  subscription_id   = rediscloud_subscription.subscription.id
  provider_name     = "GCP"
  gcp_project_id    = data.google_compute_network.network.project
  gcp_network_name  = data.google_compute_network.network.name
}

resource "google_compute_network_peering" "subscription-peering" {
  name         = "redislabs-rl-${rediscloud_subscription_peering.subscription-peering.gcp_redis_network_name}"
  network      = data.google_compute_network.network.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${rediscloud_subscription_peering.subscription-peering.gcp_redis_project_id}/global/networks/${rediscloud_subscription_peering.subscription-peering.gcp_redis_network_name}"
}

```

### Debug Output
# rediscloud_subscription_peering.subscription-peering must be replaced
-/+ resource "rediscloud_subscription_peering" "subscription-peering" {
      + aws_account_id         = (known after apply)
      + aws_peering_id         = (known after apply)
      + gcp_network_name       = "**_VPCNAME_**"
      + gcp_peering_id         = (known after apply)
      + gcp_project_id         = "**_PROJECTID_**"
      + gcp_redis_network_name = (known after apply)
      + gcp_redis_project_id   = (known after apply)
      ~ id                     = "**_ID/ID_**" -> (known after apply)
      + provider_name          = "GCP" # forces replacement
      + region                 = (known after apply)
      ~ status                 = "active" -> (known after apply)
      + subscription_id        = "**_ID_**" # forces replacement
      + vpc_cidr               = (known after apply)
      + vpc_id                 = (known after apply)

      - timeouts {}
    }

### Expected Behavior
Terraform should have state "Nothing to change".

### Actual Behavior
Terraform wants to replace the redis peering

### Steps to Reproduce
1. Manually create a peering on redislabs console.
2. Terraform import the redis peering
1. `terraform plan`

**Comment by nir-redis** [comment]
Fix released on version v0.2.2. Closing the issue
