### ISSUE TITLE
Creation of DB with modules fails in exiting subscription if the cluster is not on the latest version

### ISSUE THREAD

**Issue by AhmedAlnoamany** [RedisLabs/terraform-provider-rediscloud#137]
Hi there,

Opening this issue on behalf of customer, in which customer is trying to add RedisJSON module via TF and getting an error 
"The module ReJSON with 1.0.7 does not exists"

The cause of the issue is the cluster in the existing subscription is not running the latest cluster version, and hence the available ReJSON module version is below 1.0.7. There is no option to specify the version in the API

### Terraform Version
Provider RedisLabs/rediscloud version is 0.2.4. 
Terraform version is 0.14.6.

### Affected Resource(s)
Database Modules

### Terraform Configuration Files

![configuration](https://user-images.githubusercontent.com/85501690/128828894-e1888d45-803b-4e12-9ec7-1084c0da857f.png)

### Debug Output

```
"taskId" : "6ebbb3f4-9115-4d53-bb0b-xxxx"

Error: 

{
5133 "taskId" : "6ebbb3f4-9115-4d53-bb0b-xxxx",
5134 "commandType" : "databaseCreateRequest",
5135 "status" : "processing-error",
5136 "description" : "Task request failed during processing. See error information for failure details.",
5137 "timestamp" : "2021-08-05T17:27:46.685Z",
5138 "response" : {
5139 "error" : {
5140 "type" : "GENERAL_ERROR",
5141 "status" : "500 INTERNAL_SERVER_ERROR",
5142 "description" : "General error occurred. Please contact Redis Labs support with your task ID"
5143 },
5144 "additionalInfo" : "The module ReJSON with 1.0.7 does not exists"
5145 },
5146 "_links" : {
5147 "self" : {
5148 "href" : "https://api.redislabs.com/v1/tasks/6ebbb3f4-9115-4d53-bb0b-xxxx",
5149 "type" : "GET"
5150 }
5151 }
5152}: timestamp=2021-08-05T17:27:47.023Z
```

### Expected Behavior
DB should be created with the available module version on the cluster.

### Actual Behavior
The API fails with error. Version 1.0.7 seems to be hardcoded. 

### Steps to Reproduce
Repro steps are just to create a DB with ReJSON module. The error depends on the cluster version available in the backend of the subscription

**Comment by nir-redis** [comment]
Solved a bug in our API which solves this issue. Not a terraform bug
