### ISSUE TITLE
Support auto-generated password for DB, or ability to disable the default user

### ISSUE THREAD

**Issue by atsui-bay1** [RedisLabs/terraform-provider-rediscloud#139]
Currently, the `database` block requires the `password` element be set.  While the actual password is hidden from the output, it is still stored in plaintext in the Terraform state, which constitutes a security risk.

The create database API can omit the password and the database will be created with an auto-generated password.  The terraform provider should expose the same functionality, while not storing the generated password in the statefile.  Alternatively, the ability to create a database without the default username/password would be useful (but I don't believe this is currently possible in the API).

### Terraform Version
`Terraform v1.0.0`

### Affected Resource(s)
- rediscloud_subscription

### Terraform Configuration Files
```
resource "rediscloud_subscription" "subscription" {
  name = "example"
  memory_storage = "ram"

  cloud_provider {
    provider = "GCP"
    cloud_account_id = "1"
    region {
      region = "us-central1"
      networking_deployment_cidr = "10.31.128.0/24"
      preferred_availability_zones = ["us-central1-a"]
    }
  }

  database {
    name = "test-db"
    protocol = "redis"
    memory_limit_in_gb = 1
    data_persistence = "none"
    throughput_measurement_by = "operations-per-second"
    throughput_measurement_value = 1000
//    password = random_password.initial_password.result
  }
}
```

### Expected Behavior
A randomly generated password is created for the database.  The password is NOT stored in the terraform state.

### Actual Behavior
```
╷
│ Error: Missing required argument
│ 
│   on redis.tf line 24, in resource "rediscloud_subscription" "subscription":
│   24:   database {
│ 
│ The argument "password" is required, but no definition was found.
╵
```

**Comment by atsui-bay1** [comment]
Another alternative would be to support the `ignore_changes` lifecycle policy on the password field so that the password could be changed through the UI/API, and then ignored for any terraform updates.  Currently this fails as the database type is a set:

```
  lifecycle {
    ignore_changes = [database[0].password]
  }
```
│ Error: Cannot index a set value
│ 
│   on redis.tf line 45, in resource "rediscloud_subscription" "subscription":
│   45:       database[0].password
│ 
│ Block type "database" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
```

**Comment by NoamSternRedis** [comment]
The password is no longer required as of Redis Cloud version 1.0.0 and above.
Closing the issue.
