### ISSUE TITLE
Support standalone database resource

### ISSUE THREAD

**Issue by atsui-bay1** [RedisLabs/terraform-provider-rediscloud#140]
The `rediscloud_subscription` resource is responsible for both the subscription and database definitions.  It would be useful to be able to specify a database outside of the `rediscloud_subscription` resource.  This would make the provider closer match the REST API resources and the `rediscloud` `data` Terraform resources.  This also supports workflows where different teams are responsible for managing the subscription and the databases.

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription

**Comment by nir-redis** [comment]
Hi @atsui-bay1, 
Thanks for raising this issue. This has been requested in the past, and rightfully so. However, the terraform provider is dependent on our APIs, and at this point we are unable to support this request. We do aim to make this change, but there is no timetable for that currently.

**Comment by fmasion** [comment]
Hello @nir-redis 

given the fact you can create a database on an already existing subscription via the REST API
https://docs.redis.com/latest/rc/api/examples/create-database/

It should be possible to make a data request to get the subscription's info and use it in a database resource creation
Am I missing something ?

The lifecycle of both resources (subscription, database) are clearly not the same subscription are mostly organisation level, and database are project/environement level....

I'm sure I could prototype something using https://github.com/Mastercard/terraform-provider-restapi

It would be cleaner to have a well structured official TF provider. 

Fred

**Comment by NoamSternRedis** [comment]
Hi @fmasion, I'm sorry for the very late response. 
Some of the issues in the registry were missed.

I'm closing this issue as we have introduced the `rediscloud_subscription_database` as part of version 1.0.0.

Let me know if something needs to be added.
Thanks, and sorry again for the delay.
