### ISSUE TITLE
Unable to create VPC peering request for GCP deployment using rediscloud provider. Seems like it is expecting a field of VPC_id despite the documentation saying that is an AWS only field.

### ISSUE THREAD

**Issue by trevmane** [RedisLabs/terraform-provider-rediscloud#143]
### Terraform Version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/google v3.84.0
+ provider registry.terraform.io/redislabs/rediscloud v0.2.4

### Affected Resource(s)
rediscloud_subscription_peering

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
https://gist.github.com/trevmane/e39247f932e4108edbde6e41a01ac82a

### Debug Output
https://gist.github.com/trevmane/289fa306189775cd89e259fdabf931fc

### Expected Behavior
We should have successfully created a VPC peering request within rediscloud, which would then be accepted by the google provider

### Actual Behavior
We got an error 400 by the API call that is leveraged to POST the VPC peering request. Here is a gist of the API call that is failing: https://gist.github.com/trevmane/e93f69393658b3aa31938fb1cd2edd73

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply (with appropriate API keys for authentication)

**Comment by nir-redis** [comment]
This issue happened due to a bug on our API. Fixed and released. no need to update terraform version
