### ISSUE TITLE
Subscription resource was tainted despite successful backend task

### ISSUE THREAD

**Issue by brentp-redislabs** [RedisLabs/terraform-provider-rediscloud#150]
Opening this on behalf of a RC customer.  When creating multiple subscription resources, the customer is only able to create one subscription resource successfully while the creation of the second resource is marked tainted.  This is suspected to be timing related with the backend API as the backend task is marked completed but the API is returning HTTP 404 still on subsequent call to `/v1/subscriptions/<subscription_id>`.  After the resource is tainted, the follow up run of the terraform manifest succeeds as expected and the second subscription is replaced.

### Terraform Version
Terraform version: 1.0.5
Provider version: 0.2.4

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
https://gist.github.com/brentp-redislabs/f2e7df6d96a0d9b743d85702b0a2421e

### Expected Behavior
Both subscriptions should have been created successfully

### Actual Behavior
The first subscription creates and the second is tainted

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Customer has a cloud contract with RC

**Comment by NoamSternRedis** [comment]
Not relevant
