### ISSUE TITLE
Where to setup data eviction policy and RBAC

### ISSUE THREAD

**Issue by siansiansu** [RedisLabs/terraform-provider-rediscloud#170]
Hi,

Is it possible to setup **Data eviction policy** and **RBAC** in terraform?  I want to use Terraform to manage Redis but I cannot find that in the documents. 

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription

Best Regards,
Alex

**Comment by nir-redis** [comment]
Hi,
RBAC is not currently in our APIs or in the terraform provider. We will make an update once it is supported.
We will look to understand why data eviction policy is not supported and make a fix

**Comment by siansiansu** [comment]
Please let me know if data eviction policy is fixed. So that, I could use terraform for our case. 
Thanks!

**Comment by stuart-c-moore** [comment]
👍 for adding the data eviction policy to the terraform provider

**Comment by siansiansu** [comment]
Big Big Thanks!!!

**Comment by NoamSternRedis** [comment]
The attribute is supported today through the resource `rediscloud_subscription_database`.
The attribute's name is `data_eviction`.

See: https://registry.terraform.io/providers/RedisLabs/rediscloud/latest/docs/resources/rediscloud_subscription_database#data_eviction
