### ISSUE TITLE
No result for data "rediscloud_cloud_account" block

### ISSUE THREAD

**Issue by qf9ar8nv** [RedisLabs/terraform-provider-rediscloud#224]
### Terraform Version
Terraform v1.1.9 on darwin_arm64

### Affected Resource(s)
Please list the resources as a list, for example:
- data, rediscloud_cloud_account

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "rediscloud_subscription" "grabit" {
  name           = "Redis-Grabit"
  memory_storage = "ram"

  cloud_provider {
    provider         = data.rediscloud_cloud_account.grabit.provider_type
    cloud_account_id = data.rediscloud_cloud_account.grabit.id
    region {
      region                       = "ap-northeast-2"
      networking_deployment_cidr   = var.networking_deployment_cidr
      preferred_availability_zones = ["ap-northeast-2a"]
    }
  }

  database {
    name                         = "Redis-Grabit-DB"
    protocol                     = "redis"
    memory_limit_in_gb           = 0.01
    password                     = var.database_password
    replication                  = "false"
    throughput_measurement_by    = "operations-per-second"
    throughput_measurement_value = 10000
  }
}
---
data "rediscloud_cloud_account" "grabit" {
  exclude_internal_account = true
  provider_type = "AWS"
  name = "redis-grabit"
}

output "cloud_account_id" {
  value = data.rediscloud_cloud_account.grabit.id
}

output "cloud_account_access_key_id" {
  value = data.rediscloud_cloud_account.grabit.access_key_id
}
```

### Expected Behavior
Apply successful

### Actual Behavior
Terraform apply is not success with error:
```
Error: Your query returned no results. Please change your search criteria and try again.
with data.rediscloud_cloud_account.grabit,
on main.tf line 63, in data "rediscloud_cloud_account" "grabit":
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

---

I made it by referring to the official provider of Ready Cloud [Provider link for data block](https://registry.terraform.io/providers/RedisLabs/rediscloud/latest/docs/data-sources/rediscloud_cloud_account), but there is an error that there is no return value.
Did I do anything wrong?

**Comment by krubot-sky** [comment]
I'm seeing the same error myself, is this being looked into?

**Comment by kamran-redis** [comment]
Do you get account data back when just using ?
```
data "rediscloud_cloud_account" "grabit" {
}
````

**Comment by krubot-sky** [comment]
So it seems to return when we don't put any data in like above however the provider seems to default to `AWS` which shouldn't be the case as this is on the `GCP` cloud. Is this being replicated on your side?

**Comment by NoamSternRedis** [comment]
Hi @krubot-sky, I'm sorry for the very long delay with the response here. It slipped under the radar.
Is this still an issue for you? Something that we can help with?
