### ISSUE TITLE
Support for database port configuration

### ISSUE THREAD

**Issue by josecalvosuarez** [RedisLabs/terraform-provider-rediscloud#294]
### Terraform Version
1.3.1

### Affected Resource(s)
- resource, rediscloud_subscription_database

### Expected Behavior
Be able to configure the database port through the provider using an argument in the rediscloud_subscription_database resource

### Actual Behavior
Currently there is no way to setup the redis port using the rediscloud_subscription_database resource. The REST API does support it, though

**Comment by danielarbiv** [comment]
Hi Jose, thank you for your feedback. We certainly plan to add it to our TF registry. The plan is to have it during the first Q of this year.
Sorry for the delay, and I hope it works for you.

**Comment by josecalvosuarez** [comment]
Awesome! Thanks for your response.

**Comment by NoamSternRedis** [comment]
Hi @josecalvosuarez, sorry for the delay, but the [port](https://registry.terraform.io/providers/RedisLabs/rediscloud/latest/docs/resources/rediscloud_subscription_database#port) is available in the registry as of a couple of months ago.
We appreciate the feedback!
