### ISSUE TITLE
Support for backup configuration

### ISSUE THREAD

**Issue by urie-tsec** [RedisLabs/terraform-provider-rediscloud#334]
### Terraform Version
Not relevant I guess

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription_database
- 
### Expected Behavior
There should be a way to configure the remote back type through terraform

### Actual Behavior
Currently doesn't look possible

I checked the redis api and saw that that configuration type is supported but not included in the go library. I guess that is why that was not implemented yet.

**Comment by NoamSternRedis** [comment]
Hi @urie-tsec, thank you for the feedback, and I'm sorry for the late response.
We are working on closing some gaps between the API and TF these days, and remote backup is one of them.

I don't have an exact ETA, but I can say it will be available in the next 2-3 months.

**Comment by NoamSternRedis** [comment]
Hi @urie-tsec, the remote backup configuration is available in our registry
