### ISSUE TITLE
Support for 0 quantity in rediscloud_subscription.creation_plan.quantity

### ISSUE THREAD

**Issue by darron** [RedisLabs/terraform-provider-rediscloud#356]
### Terraform Version
I don't think this is a Terraform version problem - but: `Terraform v1.3.9 on darwin_arm64`

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription

### Terraform Configuration Files
```hcl
resource "rediscloud_subscription" "subscription" {
  name = var.subscription_name

  cloud_provider {
    provider = "GCP"
    region {
      region                       = var.region
      multiple_availability_zones  = var.multiple_availability_zones
      networking_deployment_cidr   = var.networking_deployment_cidr
      preferred_availability_zones = var.preferred_availability_zones
    }
  }

  creation_plan {
    average_item_size_in_bytes   = var.average_item_size_in_bytes
    memory_limit_in_gb           = var.memory_limit_in_gb
    quantity                     = 0
    replication                  = var.replication
    support_oss_cluster_api      = var.support_oss_cluster_api
    throughput_measurement_by    = var.throughput_measurement_by
    throughput_measurement_value = var.throughput_measurement_value
    modules                      = var.modules
  }
}
```

### Debug Output
Both `0` and `1` quantity JSON sent to Rediscloud is posted here:

https://gist.github.com/darron/f243f9dcb33f229651a60bc4b7a1c2f3

### Expected Behavior

I want to create a `rediscloud_subscription` for an entire product vertical without ANY databases.

Inside that product vertical there will be multiple environments: `dev`, `staging` and `production`.

I don't NEED or WANT all of the Redis instances to be the same size.

I want to setup all my Redis databases individually using the `rediscloud_subscription_database` resource.

I also want to define the `rediscloud_subscription` in my `common` environment and then use the same subscription in my other Terraform environments - which are all separate Terraform states.

Is there a reason why we must pick at least `1` for `rediscloud_subscription.creation_plan.quantity`?

I updated the provider locally - and y'all send back a `400` when I do that:

https://gist.github.com/darron/808996e48e6c6b9b9a2c4db6eb858f97

I looked through the web interface - and it looks like I can't just create a Subscription there either.

![Screenshot 2023-03-08 at 2 36 09 PM](https://user-images.githubusercontent.com/5176/223855967-6ac29e87-0884-4878-b800-bfe698101da9.png)

We can't upgrade from `0.2.9` because of these - there's no real workaround that I can see:

1. I can't setup TLS properly this way.
2. I can't set the password like we have been doing.

Am I missing something? I might totally be wrong - would love to find out a different way to do this.

### Actual Behavior

I am forced to create a Redis instance with the settings that are specified in `creation_plan`.

### Steps to Reproduce

Create a `rediscloud_subscription` with `0` in `creation_plan.quantity`.

Can't do that.

### Important Factoids

We're on GCP.

### References

I couldn't find any.

**Comment by darron** [comment]
Also - thank you for making it easy to test a new provider - that little bit of `GNUmakefile` and associated script was a nice sweetener when I went to test it out.

**Comment by NoamSternRedis** [comment]
Hi Darron, thank you for the feedback.

The terraform provider uses the Cloud API in the background, which necessitates DB metadata (tight coupling between the subscription and its DBs). 
What Redis Cloud provider > 1.0.0V does in the “creation_plan” block is it uses the DB parameter to initially create the cluster infrastructure with the “dummy” databases but then deletes them in the background once done. Therefore, no databases will be created in reality, they are used to help provision optimized infrastructure. 
Then, you can use the `rediscloud_subscription_database` resource to create ‘actual’ databases. The goal is to configure the `creation_plan` as close as possible to the databases that will live as part of the subscription. Having said that, Redis will create and provision sufficient infrastructure for your databases, even if they aren’t the same as the ones specified in the creation_plan.

I hope that helps answer your question.

**Comment by darron** [comment]
Hey @NoamSternRedis - thanks for the response - the email for this went to a different account so I didn't see it.

Appreciate the explanation. I do understand why you guys have done it - I guess it would work optimally for us if we grouped our similar sized databases together - and we might need to do that.

With the previous provider, because of the way it was constructed, we had ended up putting a single instance per / subscription - which we found out from your team is a tremendously expensive way to organize them.

When I tested with a single `quantity` in `creation_plan` - I saw an instance created when the subscription was created:

![during](https://user-images.githubusercontent.com/5176/226057451-78cf89b4-872c-4db2-8b21-62eb391f5171.jpeg)

Which then disappeared:

![after](https://user-images.githubusercontent.com/5176/226057478-afb5b9ae-7ede-4815-95a5-e2c9a3ebe083.jpeg)

How we wanted to use the new provider was by grouping our Redis clusters together in a vertical having:

1. dev
2. staging
3. production

in a single subscription. That means one product's Redis can't interfere with another product's Redis - and so on. Then we could figure out each product's Redis costs very simply as well.

Unfortunately those instances have very different performance characteristics - which y'all are saying may be a problem due to `creation_plan` being `used to help provision optimized infrastructure`.

That's not optimal for us - but it is the way it currently is.

I'd like to humbly ask if y'all would re-consider that - or add the ability to change that - but totally understand if it's not possible.

At this point - I'll close the issue - we've found a workaround and I guess we'll end up seeing if the performance of our databases is affected enough by `creation_plan` to be a problem.

We have loved Redis Enterprise's product - it's great - we don't have to worry about it and have had minimal problems - thanks again for your response.

**Comment by NoamSternRedis** [comment]
Hi Darron - thank you again for elaborating on your use case.

I understand your concern, as you can't create DBs with the exact specification using the `creation_plan` as it's limited the users to have a maximum of 1 spec with some quantity.
We decided to have it that way because we wanted to simplify the users' experience when creating a subscription. We wanted to eliminate as many attributes as possible from the `creation_plan` block as it represents 'dummy' databases.
As you mentioned, your use case is not exactly compatible with this.

Having said that, any of your databases' performance will not be harmed by the difference between the `creation_plan` block and the actual databases you will create afterward. Redis will ALWAYS create at least the infrastructure that is needed to ensure sufficient resources to support your databases. So if someone "suffers" from this mismatch, it is Redis that will likely create a bit more resources than needed.

Thank you again for your insights and recommendations, be sure they are taken into consideration.
