### ISSUE TITLE
Support Create User and ACL for each DB

### ISSUE THREAD

**Issue by RiddlerKnight** [RedisLabs/terraform-provider-rediscloud#375]
## Feature proposal
Support Create User and ACL for each DB.

### Expected Behavior
For governance perspective, I need to keep users and roles for each service as code and integrates with pipeline to automatically create a new user when a new service is coming up.

### Similar use case
This proposal is similar to `elasticache_user` in aws provider.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user

**Comment by NoamSternRedis** [comment]
Hi @RiddlerKnight, we have ACLs support (and user as part of it) in our provider.
