### ISSUE TITLE
Planned support for `/fixed/*` API? 

### ISSUE THREAD

**Issue by gtebbutt** [RedisLabs/terraform-provider-rediscloud#389]
Hi, I just wanted to check if there's anything on the roadmap to add support for the new fixed plan API endpoints? It'd be a huge help to our workflow to be able to include those resources in terraform along with the rest of our config. 

### References
- https://github.com/RedisLabs/terraform-provider-rediscloud/issues/118 (closed in 2021)

**Comment by cHiv0rz** [comment]
I'm interested into this feature as well. Specially since I can see the endpoints for `fixed` in Swagger, but there is no any reference into the official documentation.

**Comment by NoamSternRedis** [comment]
Hi @gtebbutt, @cHiv0rz, 
We are considering adding support for Fixed endpoints to our TF provider. As for now, we are still evaluating it, and it's not part of the roadmap. As you said, we have recently added support for Fixed endpoints to our API.
I'll update once I have a clearer view. 
Appreciate the feedback. It's totally something that we'll take into consideration!

**Comment by phlundblom** [comment]
So, I've spent a couple of hours with the Terraform provider trying to set up a database on a fixed plan subscription without success. It is not obvious (or even mentioned?) in the provider documentation that fixed plan isn't supported.

The fact that a TF provider existed was one of the reasons for choosing this specific cloud infrastructure setup and now I find out fixed isn't supported. Pretty disappointing :(

**Comment by NoamSternRedis** [comment]
I'm sorry for your experience. I pushed documentation fixes to specify on the `rediscloud_subscription` and `rediscloud_subscription_database` that they can provision Flexible subscriptions only.

I will update here once I have an ETA on the Fixed subscription/database support.

**Comment by mazerte** [comment]
+1 very important feature for early stage startup because Flexible plan start at ~$1/h ($720/month). It will help to access the Fixed pricing with Terraform to easily upgrade when needed.

**Comment by nibblesnbits** [comment]
+1 here.  $20/mo vs ~$700/mo makes a pretty big difference with my small business.

**Comment by NoamSternRedis** [comment]
Hi all, I'm happy to say we released support for Fixed resources in our registry as part of version 1.7! 
Note - we renamed our deployments types:
Fixed - now called Essentials
Flexible - now called Pro

@gtebbutt @cHiv0rz @phlundblom @mazerte @nibblesnbits FYI
