### ISSUE TITLE
client_tls_certificates not supported

### ISSUE THREAD

**Issue by atsui-bay1** [RedisLabs/terraform-provider-rediscloud#479]
### Terraform Version
Terraform v1.3.6

### Affected Resource(s)
Please list the resources as a list, for example:
- rediscloud_subscription_database
- rediscloud_active_active_subscription_database

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
`clientTlsCertificates` is a valid field in the API to upload multiple TLS certificates.  The listed resources currently only supported the deprecated  `clientSslCertificate` as `client_ssl_certificate`

### Actual Behavior
`An argument named "client_tls_certificates" is not expected here.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by JohnSharpe** [comment]
Hi @atsui-bay1, thanks for the report.
Please give the `client_tls_certificates` property a whirl in 1.8.0 and let us know if you run into any problems.
Cheers!

**Comment by atsui-bay1** [comment]
Hi @JohnSharpe Tested this out and the fix works well!  However, the new property does not show up on the Terraform provider documentation.  I've opened https://github.com/RedisLabs/terraform-provider-rediscloud/pull/558 to update the docs.
