### ISSUE TITLE
Not enough information to create GCP peering

### ISSUE THREAD

**Issue by romanlv** [RedisLabs/terraform-provider-rediscloud#66]
Hi there,

I'm trying to use `rediscloud_subscription_peering` resource with GCP provider name. It successfully creates peering in RedisLabs, but I cannot figure out how to create peering in GCP using TF.

When I create peering manually using UI it gives me a gcloud command to run e.g. 

`gcloud compute networks peerings create rl-cxxx-europe-west3-1-rlrcp --project xyz --network bbb-vpc-xyz --peer-network=cxxx-europe-west3-1-rlrcp --peer-project=eddxxx-tp --auto-create-routes`

there is 
- `peer-network`
- `peer-project` 

rediscloud_subscription_peering output does not provide either,  but `rediscloud_subscription` output has 

```
      + cloud_provider                = [
          + {
              + cloud_account_id = "1"
              + provider         = "GCP"
              + region           = [
                  + {
                      + multiple_availability_zones  = false
                      + networking_deployment_cidr   = "10.0.0.0/24"
                      + networking_vpc_id            = ""
                      + networks                     = [
                          + {
                              + networking_deployment_cidr = "10.0.0.0/24"
                              + networking_subnet_id       = ""
                              + networking_vpc_id          = "cxxx-europe-west3-1-rlrcp"  <!--- `peer-network`
                            },
                        ]
                      + preferred_availability_zones = []
                      + region                       = "europe-west3"
                    },
                ]
            },
        ]

``` 
 
 
But how to find out `peer-project` in RedisLabs GCP?

**Comment by romanlv** [comment]
[Redis api](https://api.redislabs.com/v1/swagger-ui.html#/Subscriptions/getVpcPeeringUsingGET) exposes both parameters in API, it looks like they just should be passed to the output

**Comment by Aviad-Abutbul** [comment]
@romanlv thanks again for reporting this. The fix is already on main, see #67. Also see #70 for an example of full flow using the gcp provider.
We are going to have a new release that will include this very soon.

**Comment by Aviad-Abutbul** [comment]
@romanlv please see release 0.2.1

**Comment by Aviad-Abutbul** [comment]
Closing this as 0.2.1 was released and should address this.
