### ISSUE TITLE
Feature request for Database as resource

### ISSUE THREAD

**Issue by SachinTS** [RedisLabs/terraform-provider-rediscloud#82]
Hello,

I have a feature request for having resources for databases with subscription id as required parameter. Right now its complicated for managing large number of database objects within rediscloud subscription resources. It also helps in managing subscription config and database config separately.  

Example: A admin can handle subscription creation and management, while a product team can manage redis database configs.

Thank you.

**Comment by ejholmes** [comment]
Ditto this. I was really excited to find out that RedisLabs built a terraform provider, but the current state makes it unusable without the ability to specify individual DB's as resources.

**Comment by bionicles** [comment]
I'd use it!

**Comment by Aviad-Abutbul** [comment]
Hi All,
Thank you for your feedback.
This is not so much related to the TF provider, but more to how Redis Cloud works.
Closing this one for now.

Thanks.

**Comment by ejholmes** [comment]
What exactly makes this hard to implement? The API allows you to create a single database under a subscription (`POST https://api.redislabs.com/v1/subscriptions/:subscription_id/databases`), which seems to map pretty well to a single Terraform resource. All that would be needed is to pass a `subscription_id` into the resource.

**Comment by Aviad-Abutbul** [comment]
Hi @ejholmes. 
Yes, you can create a database inside an existing subscription.
The problem starts when you don't have any subscription resource in place but you want to create a database resource.
(1) When you create a subscription you must specify which database(s) to create in it.
(2) When you create a database, you must associate it with the relevant subscription.

From (1)+(2) we ended up with the conclusion that a database cannot be represented as a standalone TF resource and we had to set a hierarchy between subscription and database.

**Comment by ejholmes** [comment]
Thanks for the clarification. For most people that would want this, I think it'd be reasonable to just have a requirement for creating a single DB when creating a subscription, and then supporting a `rediscloud_db` resource for any subsequent DB's. Just my 2 cents.
