### ISSUE TITLE
TLS configuration missing from database data & resource

### ISSUE THREAD

**Issue by OJFord** [RedisLabs/terraform-provider-rediscloud#89]
We'd like to be able to set database client certificates, and enforce/not enforce them, in terraform - this is supported by the API, but isn't currently an available attribute (at least, not per docs). (Nor is it possible to retrieve existing ones via `data "rediscloud_database"`.)

It would also be convenient to be able to retrieve the Redis Labs CA via a data source.

Many thanks.

**Comment by Aviad-Abutbul** [comment]
Hi @OJFord, you can specify `"client_ssl_certificate"` in the `database` block on `rediscloud_subscription` resource

**Comment by OJFord** [comment]
Thanks, I think I expected it to be on the database resource because that's how it works in the web UI - seems you can have a different client certificate for each?

`data` access to the RL CA cert would be useful too, which doesn't seem to exist.

That said I actually don't personally have a use for this any more, since I discovered after opening the issue that though the API is available, it actually only returns any content if you're on the 'Flexible' plan, which unfortunately we're not. (RL#70330)

**Comment by NoamSternRedis** [comment]
Closing as it's already supported as part `rediscloud_subscription_database` resource
