### ISSUE TITLE
Please support multi-module 

### ISSUE THREAD

**Issue by bionicles** [RedisLabs/terraform-provider-rediscloud#91]
### Terraform Version
latest / not using it right now

### Affected Resource(s)
- rediscloud_subscription

### Panic Output
n/a 

### Expected Behavior
We ought to be able to enable multiple modules (Search, Graph, JSON) so we can search graphs and JSON.

modules:  ['redisgraph', 'redisearch', 'redisjson']

ideally the details of order would be handled internally (i.e. if redisearch needs to come before others to index them), then this list could be re-sorted accordingly  

### Actual Behavior
the max number of items in the list is set to 1 so you can't do this right now
also, it's called "module" when we'd ideally call it "modules" plural

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
https://github.com/RedisLabs/terraform-provider-rediscloud/blob/6895d80cec470d670b2eb4cb476dc35b36b8e7be/internal/provider/resource_rediscloud_subscription.go#L356

### References
```
"module": {
	Description: "A module object",
	Type:        schema.TypeList,
	Optional:    true,
	**MinItems:    1,
	MaxItems:    1,**
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Description: "Name of the module to enable",
				Type:        schema.TypeString,
				Required:    true,
			},
		},
	},
},
```

**Comment by nir-redis** [comment]
Thanks for raising the issue. This is not a terraform issue, currently in our cloud offering, you can only use one module. we are working on it, and the terraform provider will be updated accordingly.
