### ISSUE TITLE
Need validation for length of the database name.

### ISSUE THREAD

**Issue by SachinTS** [RedisLabs/terraform-provider-rediscloud#99]
Hi there,

### Affected Resource(s)
rediscloud_subscription

### Error output
```
Error: 400 BAD_REQUEST - BAD_REQUEST: Bad request detected. Please see additional info for more details
```

### Debug Output
```
"additionalInfo" : "Database name is longer than 40 characters"
```

### Expected Behavior
Validate database name in `terraform plan` and exit

### Actual Behavior
No validation from the provider, fails during `terraform apply`

### Steps to Reproduce
set database name with string with length longer the 40.

**Comment by nir-redis** [comment]
Fix released on version v0.2.2. Closing the issue
